### ISSUE TITLE
Can't stop library from logging in Azure Databricks , It writes to much logs

### ISSUE THREAD

**Issue by yehiaelsayed** [fredysomy/pysonDB#12] opened 2021-06-28 13:52 UTC
Thanks for the awesome library but I am facing a small issue here I am using the library in Azure Databricks to write some logs 
but the library for some reason changing the log level for the cluster machines to be DEBUG so it makes it write to many logs 
like the image below so if you can provide a way to stop or change the log level it will be great  

Edit: 
I believe the issue is here https://github.com/fredysomy/pysonDB/blob/29c1d363aac33c8c6e332d27e3043f52a7f54f60/pysondb/db.py#L12 

![image](https://user-images.githubusercontent.com/12682179/123646889-ad2b5b00-d838-11eb-9680-abf64dab2fcd.png)

**Comment by fredysomy** [comment] 2021-06-28 14:00
Hey @yehiaelsayed .

This log issue was solved in #10 .

you can turn off the logs using
```
a = db.getDb("test.json", log=False)  # the logs are turned off
```
Please try it out and check if this works , else ping me and i will find a remedy.

thanks for using this library.

**Comment by fredysomy** [comment] 2021-06-28 14:00
@Adwaith-Rajesh

**Comment by yehiaelsayed** [comment] 2021-06-28 15:03
@fredysomy 
Thank you so much for the quick response but this is not solving the issue 
as I mention before this line below 
https://github.com/fredysomy/pysonDB/blob/29c1d363aac33c8c6e332d27e3043f52a7f54f60/pysondb/db.py#L12

is changing the global configuration for the logging and when I try to change it again it is not effecting 
so I overcome the issue with this workaround 
```
import logging 
logging.basicConfig(level=logging.ERROR)
from pysondb import db
```
I am setting the log level before it is being set in the library and it is working in this way

**Comment by fredysomy** [comment] 2021-06-28 15:57
Can you join the discord disscusion group

**Comment by fredysomy** [comment] 2021-06-28 16:21
Can you tell me the version you are using.

current version is **v1.1.1**

Without log

> ![image](https://user-images.githubusercontent.com/65971072/123670208-9695fb80-d85a-11eb-8384-98ce9fe0e52d.png)

with log.(log=True)

> ![image](https://user-images.githubusercontent.com/65971072/123670103-79f9c380-d85a-11eb-9b92-ac8ef19524bf.png)

forgive me if i did'nt get your point this day was stressfull.

**Comment by Adwaith-Rajesh** [comment] 2021-06-28 17:25
@yehiaelsayed the package does not change the log level. It straight up disables logging when you use the `log` keyword.

So I don't think it's caused by pysondb. 
If no logs are shown form other packages when you use `log=False` then it's an issue.

**Comment by Adwaith-Rajesh** [comment] 2021-06-29 04:20
@yehiaelsayed PysonDB does changes the log level, if imported before other packages it does cause the effects you have mentioned. The workaround you specified is correct and that is exactly how I would use any other package that changes log level. I don't think there is anything to change in the PysonDB, and you also found a workaround for it. Trying to fix this issue is actually causing other issues as things that need to be logged are not logged and so on.

**Comment by fredysomy** [comment] 2021-06-29 04:54
@yehiaelsayed , i will be adding this workaround  which you did to docs , if this happens to someone else in future.

**Comment by Adwaith-Rajesh** [comment] 2021-06-29 05:06
this issue can be closed.

**Comment by fredysomy** [comment] 2021-06-29 05:10
Closing this issue.

**Closed by fredysomy** 2021-06-29 05:10 UTC

**Comment by yehiaelsayed** [comment] 2021-06-29 09:29
@fredysomy @Adwaith-Rajesh 
sorry for troubling you guys, but setting `log=False` will stop the library logs but the case is this line 
` logging.basicConfig(level=logging.DEBUG) ` changing the configuration for the `py4j` logging so it keeps writing all logs from `debug` level  so it is the `py4j` logs, not `pythondb` logs (you can check the screenshot in the first message) 
and I believe it will cause the same issue with anyone has a dependency on the same logging module because as per the 
documentation ` logging.basicConfig(level=logging.DEBUG) ` this line apply the configuration on the logger root level 

https://docs.python.org/3/library/logging.html#logging.basicConfig
![image](https://user-images.githubusercontent.com/12682179/123769726-a35a3400-d8da-11eb-9486-be7a3e24da12.png)

so I believe you should use `setLevel` function on your logger level to avoid changing the root logger configuration 
https://docs.python.org/3/library/logging.html#logging.Logger.setLevel
![image](https://user-images.githubusercontent.com/12682179/123773795-f4b7f280-d8dd-11eb-9444-13e6afe17af9.png)

**Comment by Adwaith-Rajesh** [comment] 2021-06-29 09:30
@yehiaelsayed will look into it. Thank for the suggestion.
